### ISSUE TITLE
A descriptor guard?

### ISSUE THREAD

**Issue by XiangpengHao** [HaoPatrick/pmwcas#17]
We should probably add a descriptor guard, so that users will not accidentally leak any descriptor.

Something like `std::unique_ptr<Descriptor> desc`

**Comment by wangtzh** [comment]
Yes. Just one quick thought: maybe construct something hidden from the user, say return a GuardedDescriptor that has (1) descriptor pointer and (2) a guard. The guard gets destructed as GuardedDescriptor goes out of range, and calls descriptor abort transparently if the user didn't call it.
